const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const dataDir = path.join(rootDir, 'data');
const outputPath = path.join(rootDir, 'assets', 'timeline-data.js');

function loadTimelineData() {
    const dataFiles = fs.readdirSync(dataDir)
        .filter((fileName) => /^copilot-timeline-\d{4}\.json$/.test(fileName))
        .sort();

    if (dataFiles.length === 0) {
        throw new Error('No timeline data files found in data/.');
    }

    const seenEntries = new Set();
    const entries = [];
    const yearly = {};
    const ranges = {};

    dataFiles.forEach((fileName) => {
        const filePath = path.join(dataDir, fileName);
        const jsonData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        const yearMatch = fileName.match(/(\d{4})/);
        const year = yearMatch ? Number(yearMatch[1]) : jsonData.metadata?.year_filter;

        yearly[year] = jsonData.metadata || {};
        ranges[year] = jsonData.metadata?.date_range || {
            earliest: null,
            latest: null
        };

        (jsonData.entries || []).forEach((entry) => {
            const normalizedEntry = {
                ...entry,
                year: entry.year || year
            };
            const dedupeKey = [normalizedEntry.date, normalizedEntry.title, normalizedEntry.url].join('|');

            if (!seenEntries.has(dedupeKey)) {
                seenEntries.add(dedupeKey);
                entries.push(normalizedEntry);
            }
        });
    });

    entries.sort((left, right) => {
        if (left.date !== right.date) {
            return left.date.localeCompare(right.date);
        }
        return left.title.localeCompare(right.title);
    });

    const years = Object.keys(yearly)
        .map(Number)
        .sort((left, right) => left - right);
    const currentYear = new Date().getUTCFullYear();
    const selectedYear = years.includes(currentYear) ? currentYear : years[years.length - 1];

    return {
        manifest: {
            generatedAt: new Date().toISOString(),
            currentYear: selectedYear,
            years,
            totalEntries: entries.length,
            ranges
        },
        yearly,
        entries
    };
}

function writeDataFile(dataset) {
    const content = `/* Generated by src/embed_data.js — do not edit manually */
const embeddedTimelineData = ${JSON.stringify(dataset, null, 4)};
`;
    fs.writeFileSync(outputPath, content);
}

const dataset = loadTimelineData();
writeDataFile(dataset);

console.log(`✅ Wrote ${dataset.manifest.totalEntries} Copilot changelog entries`);
console.log(`📅 Years available: ${dataset.manifest.years.join(', ')}`);
console.log(`📄 Written to ${outputPath}`);
